# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 08:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pwmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 30, 8, 29, 23, 966693, tzinfo=utc)),
        ),
    ]
