# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pwmanager', '0002_password_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
