# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 04:03
from __future__ import unicode_literals

from django.db import migrations, models
import pwmanager.models


class Migration(migrations.Migration):

    dependencies = [
        ('pwmanager', '0003_auto_20170530_0829'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingDeviceRequest',
            fields=[
                ('code', models.CharField(default=pwmanager.models.random_code, max_length=256, primary_key=True, serialize=False)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
    ]
