# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import pwmanager.models


class Migration(migrations.Migration):

    dependencies = [
        ('pwmanager', '0004_pendingdevicerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedToken',
            fields=[
                ('token', models.CharField(default=pwmanager.models.random_code, max_length=256, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='pendingdevicerequest',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
