# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 08:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pwmanager', '0005_auto_20170621_0821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pendingdevicerequest',
            old_name='date',
            new_name='date_created',
        ),
    ]
