# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwmanager', '0007_remove_pendingdevicerequest_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizedtoken',
            name='expiry_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
